name: Download petrol price data
run-name: Download petrol price data

on:
  schedule:
    - cron: '23 23 23 * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  download:
    name: Download data
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download data file
        run: |
          export TS=$(date -u "+%Y%m%dT%H%M%SZ")
          curl -o "${{ github.workspace }}/data/${TS}.json" "https://iswebsitegraphdata.informedsources.com/api/ChartData?country=1"
          echo ${TS} >> ${{ github.workspace }}/data/all.txt
      - name: Push data file to repository
        run: |
          cd ${{ github.workspace }}
          git config user.name $(git show --no-patch --format="%an")
          git config user.email $(git show --no-patch --format="%ae")
          git add data/*
          git commit -m "Download data file $(date -u "+%Y-%m-%d")"
          git push
      - run: echo "✅ This job's status is ${{ job.status }}."

  pages:
    name: Deploy to GitHub Pages
    needs: download
    uses: ./.github/workflows/pages.yml
