name: Download petrol price data
run-name: Downloading petrol price data

on:
  schedule:
    - cron: '23 3 * * 0'

jobs:
  Download-Petrol-Price-Data:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Download data file
        run: curl -o "data/$(date -ju "+%Y%m%dT%H%M%SZ").json" "https://iswebsitegraphdata.informedsources.com/api/ChartData?country=1"
      - run: echo "✅ This job's status is ${{ job.status }}."