name: Download petrol price data
run-name: Downloading petrol price data

on:
  schedule:
    - cron: '23 3 * * 0'
  workflow_dispatch:

jobs:
  Download-Petrol-Price-Data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: pwd
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Download data file
        run: curl -o "${{ github.workspace }}/data/$(date -u "+%Y%m%dT%H%M%SZ").json" "https://iswebsitegraphdata.informedsources.com/api/ChartData?country=1"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Push data file to repository
        run: |
          cd ${{ github.workspace }}
          git config user.name $(git show --no-patch --format="%an")
          git config user.email $(git show --no-patch --format="%ae")
          git add data/*
          git commit -m "Download data file $(date -u "+%Y-%m-%d")"
          git push
      - run: echo "✅ This job's status is ${{ job.status }}."